services:
  - type: web
    name: legalrag
    env: docker
    port: 3000
    region: ohio
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false # You will manually enter this in the Render dashboard
